### PR TITLE
[iCalendar] Added support for Command Tags in Events Descriptions (#1)

### PR DESCRIPTION
**Pull request by andrewfg**
### **Description**

Each calendar event may include one or more Command Tags in its description (body) text. These Command Tags are used to issue commands directly to other Items in the system when the event begins or ends. The syntax of the tags must consist of three or four fields as follows..

	BEGIN:Item_Name:New_State_Value  
	BEGIN:Item_Name:New_State_Value:Authorization_Code  
	END:Item_Name:New_State_Value  
	END:Item_Name:New_State_Value:Authorization_Code  

The first field **must** be either `BEGIN` or `END`. If it is `BEGIN` then the command will be executed at the beginning of the calendar event. Whereas if it is `END` then the command will be executed at the end of the calendar event. A calendar event may contain both multiple `BEGIN` tags and/or multiple `END` tags. If an event contains both `BEGIN` and `END` tags, this allows the respective Items (say) to be turned ON at the beginning of an event and turned OFF again at the end of the event.
 
The `Item_Name` field can be (must be) the name of any Item in the system.

The `New_State_Value` is the new state value that will be sent to the Item. It must be a value which is compatible with the Item type (QuantityType, Number, PercentageType, SwitchType, String, HSB). For example..

	23.4°C		(QuantityType:Temperature)
	12.3m/s		(QuantityType:Speed)
	ON, OFF		(Switch, OnOffType)
	33%		(Rollershutter, PercentageType)
	33%		(Dimmer, PercentageType)
	12.34 		(Number)
	any text	(StringType)
	"on"		(StringType) (use this form to force StringType)
	'on'		(StringType) (use this form to force StringType)
	UP, DOWN	(RollershutterType)
	OPEN, CLOSED	(ContactType) 
	PLAY, PAUSE	(PlayPauseType)
	FASTFORWARD	(RewindFastForwardType)
	120,100,100	(Color, HSBType)		 

The `Authorization_Code` may optionally be used as follows:

- When the Thing Configuration Parameter `authorizationCode` is a non empty string, the binding will compare the `Authorization_Code` field to the `authorizationCode` Configuration Parameter, and it will only execute the command if the two strings are the same.

- When the Thing Configuration Parameter `authorizationCode` is an empty string, the binding will NOT check this Authorization_Code field, and so it will always execute the respective command.

### **Examples**

	BEGIN:Calendar_Test_Temperature:12.3°C:abc
	END:Calendar_Test_Temperature:23.4°F:abc
	
	BEGIN:Calendar_Test_Switch:ON:abc
	END:Calendar_Test_Switch:OFF:abc
	
	BEGIN:Calendar_Test_String:the quick:abc
	END:Calendar_Test_String:brown fox:abc
	
	BEGIN:Calendar_Test_Number:12.3:abc
	END:Calendar_Test_Number:23.4:abc
		
	BEGIN:Calendar_Test_Pressure:12.3hPa:abc
	BEGIN:Calendar_Test_Speed:12.3m/s:abc
	
	BEGIN:Calendar_Test_Player:PLAY:abc
	BEGIN:Calendar_Test_Player:REWIND:abc
	
	BEGIN:Calendar_Test_RollerShutter:UP:abc
	BEGIN:Calendar_Test_RollerShutter:50%:abc
	
	BEGIN:Calendar_Test_Dimmer:OFF:abc
	BEGIN:Calendar_Test_Dimmer:50%:abc
		
	BEGIN:Calendar_Test_String:"off":abc
	END:Calendar_Test_String:'on':abc

### CODE REVIEW

**Comment by andrewfg** [comment]
@daMihe here is the PR from my Command Tag extensions to your code; unfortunately it seems to have also picked up a couple of changes that I am in process making to the tado binding; and I don't know how to remove them from your review..

**Comment by andrewfg** [comment]
> unfortunately it seems to have also picked up a couple of changes that I am in process making to the tado binding

Note: I have resolved this now.

**Comment by daMihe** [comment]
Hi @andrewfg,

first thank you for your effort. I tried to compile and test your changes but i was not able to do it. There are several problems with the current situation:

- Your code does not compile with `mvn clean install -pl :org.openhab.binding.icalendar` inside the bundles-directory. There are some small issues with `@Nullable` confusions (easy to fix, either test for null or remove the `@Nullable` in the abstract class).
- You changed the test data so the tests won't pass anymore
- There are unit tests missing (which should be done for the logic finding events, this is my demand as it ensures the logic is working even in further updates)
- You use `ArrayList` instead of `List` for an logical interface (in this case: `AbstractPresentableCalendar`) which is bad style
- You did not write yourself into the copyright into the Inital-contribution line in classes you modified. You can do that if you want.
- not all commits are signed off (this is required by openhab's MR-check, maybe it's now required to create a new MR as your commits are now already known by github and amending to your commit's may now destroy the git log)

Please fix these issues first before continuing with further functionality.

**Comment by andrewfg** [comment]
> Your code does not compile with mvn clean install 

Fixed the @Nullable annotations.

> You changed the test data so the tests won't pass anymore

I reverted your Test.ics file and instead I have added a new Test3.ics file which contains tests for the Command Tag functionality

> You use ArrayList instead of List for an logical interface (in this case: AbstractPresentableCalendar) which is bad style

Fixed.

> You did not write yourself into the copyright into the Inital-contribution line 

Done.

> not all commits are signed off

I have "touched" all the files, and added a Sign Off to the new commit..

> There are unit tests missing (which should be done for the logic finding events, this is my demand as it ensures the logic is working even in further updates)

Can you please be more specific about what tests you demand to have?

**Comment by andrewfg** [comment]
> There are unit tests missing (which should be done for the logic finding events, this is my demand as it ensures the logic is working even in further updates)

I added some unit tests: => please confirm if you are happy with them

**Comment by daMihe** [comment]
Thank you for your additions and fulfilling my demands, it works great for sample events with a virtual switch. I have also tested the binding's behaviour after your changes and did not find anything unexpected.

There are now only one thing left:
commit 295815ae2d409f88075d2bbdcf9b0d9a3de24299 is not signed off, this will block merging into openhab-addons/master. You may try [recommiting](https://stackoverflow.com/a/15667644/1354246), please make a backup before. If this does not work, please create a new branch with only the changes needed and commit at once. This however requires a new PR. Also this commit itself has nothing to do with iCalendar which may confuse reviewers and block their acceptance.

The code itself is good, i will accept the MR after that fix. Thank you again for your work on this feature.

**Comment by andrewfg** [comment]
I really HATE GIT !!

Unfortunately I could not re-sign the old wrong commit concerning the Tado binding.

So I created a new branch, and created a new PR for it here..

https://github.com/daMihe/openhab2-addons/pull/2

However, in the new PR it now shows 6500 files have changed, instead of the 13 files that I have actually changed. So I suppose that either you or I need to rebase something. But I have absolutely no idea how to do that.

**Comment by andrewfg** [comment]
Yet another new PR (now with only the 13 files which have actually changed)

https://github.com/daMihe/openhab2-addons/pull/3

**Comment by daMihe** [comment]
A big thank you for rebuilding the changes again! Merged #3 instead of this one.

**Pull request closed without merging**
